sudo: required
services:
  - docker

before_install:
  - docker build -t nayaran/docker-react  -f Dockerfile.dev .

script:
  - docker run -e CI=true nayaran/docker-react npm run test
#language: generic
